# Generated by Django 5.1.4 on 2024-12-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_standalonestl'),
    ]

    operations = [
        migrations.CreateModel(
            name='STLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='stl_files/')),
            ],
        ),
    ]
