# Generated by Django 5.1.4 on 2024-12-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG')], max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('initial_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in grams', max_digits=6)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, help_text='Low stock threshold in grams', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material_type', models.CharField(max_length=100)),
                ('stl_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
