# Generated by Django 4.2.16 on 2024-11-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG')], max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('initial_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in grams', max_digits=6)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, help_text='Low stock threshold in grams', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_material_usage', models.DecimalField(decimal_places=2, help_text='Material usage in grams', max_digits=6)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.material')),
            ],
        ),
    ]
