version: "3.9"

services:
  web:
    build: .
    container_name: print_manager_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the current directory into the container
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key  # Replace with an actual key or use environment variables
      - DATABASE_URL=postgres://user:password@db:5432/yourdb
    command: ["sh", "-c", "python manage.py migrate && python manage.py create_superuser && python manage.py runserver 0.0.0.0:8000"]

  db:
    image: postgres:13
    container_name: print_manager_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: